Add packaging setup with hatch and scikit-build-core
AvenirHealth-org/GoalsARMPython pull request #1
Opened 2024-10-08 15:09 UTC by r-ash

2025-01-28 10:16 UTC, r-ash reviewed
The `uv` docs are very good if you want to check what any of these things do. But for a quick overview.

* `uv sync` will check dependencies are up to date, and C++ code is compiled
* `uv run` will run a command e.g. pytest with `uv run pytest` or a script `uv run ./scripts/my_script.py`
* `uv build` will build source distributions and wheels from code
* `uv add` will add a new dependency

You can pass flags to these, important ones are
* `--reinstall` - this will reinstall all dependencies, and recompile the C++
* `--reinstall-package goals` - this will reinstall just goals package, recompiling the C++

uv manages package versions via a lockfile, kind of like npm `package-lock.json` this fixes package versions so when you run `uv sync` it installs the version specified in the lock file.

2025-01-28 10:16 UTC, r-ash commented on pyproject.toml
> +GOALS_ARM_GIT_TAG = "scikit-build"
We should switch this to main once the GoalsARM PR is merged

2025-01-28 10:16 UTC, r-ash commented on .python-version
> +3.10
This tells uv the default version of python to use

2025-01-28 10:16 UTC, r-ash commented on CMakeLists.txt
> +if(DEFINED ENV{LOCAL_BUILD} AND "$ENV{LOCAL_BUILD}" STREQUAL "true")
Important bit in this CMake file is that we can switch between a local GoalsARM (for if we want to debug in development work) and GoalsARM from GitHub.

2025-01-28 10:16 UTC, r-ash commented on README.md
> +source .venv/bin/activate
Note that with `uv` you shouldn't have to activate the venv, run everything with `uv run` and it will manage this for you

2025-01-28 10:16 UTC, r-ash commented on README.md
> +uv run pytest --cov --cov-config=pyproject.toml
Note, unlike hatch uv does not have a nice aliases feature, that is in the works though so hopefully soon

2025-01-28 10:16 UTC, r-ash commented on pyproject.toml
> +GOALS_ARM_GIT_TAG = "ci"
We should reset this to main once this branch is merged in

2025-01-29 00:14 UTC, rlglaubius commented on README.md
> +source .venv/bin/activate
Would be good to add a note here that the steps for activating the virtual environment are different for Windows. The path will be `.venv\Scripts\activate`, which can be run directly from the `cmd` terminal (though Powershell will throw an ugly error because it disables scripts by default).

2025-01-29 00:15 UTC, rlglaubius commented on README.md
> +uv run pytest --cov --cov-config=pyproject.toml
I'm happy either way, the key for me is good documentation of the steps, which you've done.

2025-01-29 00:35 UTC, rlglaubius requested changes
I'm pleased with how this is working. I have a couple of suggested changes for the README, then think this is good to go:

1. In the README, I was not able to do Step 3 of the VSCode IDE integration process as written. VSCode would not let me switch my Python interpreter (it may be necessary to toggle an option somewhere in VSCode to enable switching this way). Instead, I used Ctrl+Shift+P, chose "Python: Create Environment", selected "Venv" then "GoalsARMPython". VSCode recognized that the environment already existed gave me the option to use it. That activated the environment and switched the interpreter. At that point I could move on to Step 4.
2. I consistently forget that launch.json has to be created. Would be good to mention this in the step about adding the Python C++ Debugger configuration to launch.json, e.g., "You may need to create a launch.json file by following the steps here https://code.visualstudio.com/docs/editor/debugging".

2025-01-29 10:17 UTC, r-ash commented
Thanks Rob, I've expanded those comments.

I wonder if on point 1, about select interpreter not working if VSCode would have picked it up after a restart. Or maybe we are on different versions of the extension or something? Bit strange, not a big issue if the alternative works ok

2025-01-29 18:08 UTC, rlglaubius commented on README.md
> +1. If you don't already have one, create a `launch.json` by following the steps [here](Open the command palette (Ctrl+Shift+P) and run "Python: Select interpreter")
This step does not look right. I think we just "here" to be a link to this: https://code.visualstudio.com/docs/editor/debugging#_launch-configurations

2025-01-29 18:12 UTC, rlglaubius requested changes
Thanks for adding the Windows step for activating the virtual environment from command line. The additional step on creating launch.json seems like it doesn't render quite right. I've left a comment with a more precise link we could use in that step.

2025-02-04 15:52 UTC, r-ash commented on README.md
> +1. If you don't already have one, create a `launch.json` by following the steps [here](Open the command palette (Ctrl+Shift+P) and run "Python: Select interpreter")
Thanks yes! Look like what I had there before was a copy and paste error! Thanks for catching that

2025-02-04 15:54 UTC, r-ash commented on pyproject.toml
> +GOALS_ARM_GIT_TAG = "scikit-build"
I've switched this over to `main` now

2025-02-06 16:26 UTC, rlglaubius approved these changes
This looks good with the latest changes. Thanks!

2025-02-07 09:40 UTC, merged